locations:
  ["Ahmedabad",
   "Bangalore",
   "Chennai",
   "Delhi",
   "Gurgaon",
   "Hyderabad",
   "Kolkata",
   "Mumbai",
   "Noida",
   "Pune",
   "Agartala",
   "Agra",
   "Ahmednagar",
   "Aizawal",
   "Ajmer",
   "Alappuzha / Alleppey",
   "Aligarh",
   "Allahabad",
   "Ambala",
   "Amritsar",
   "Anand",
   "Ankleshwar",
   "Asansol",
   "Aurangabad",
   "Baddi",
   "Bhagalpur",
   "Bareilly",
   "Baroda / Vadodara",
   "Belgaum",
   "Bellary",
   "Bharuch",
   "Bhatinda",
   "Bhavnagar",
   "Bhilaigarh",
   "Bhopal",
   "Bhubaneshwar",
   "Bhuj",
   "Bidar",
   "Bilaspur",
   "Bokaro",
   "Chandigarh",
   "Cochin / Kochi / Ernakulam",
   "Coimbatore",
   "Cuttack",
   "Dalhousie",
   "Daman",
   "Dehradun",
   "Dhanbad",
   "Dharamsala",
   "Dharwad",
   "Dispur",
   "Durgapur",
   "Erode",
   "Faizabad",
   "Faridabad",
   "Gandhinagar",
   "Gangtok",
   "Ghaziabad",
   "Goa",
   "Gorakhpur",
   "Gulbarga",
   "Guntur",
   "Guwahati",
   "Gwalior",
   "Haldia",
   "Hisar",
   "Hosur",
   "Hubli",
   "Idukki",
   "Imphal",
   "Indore",
   "Itanagar",
   "Jabalpur",
   "Jaipur",
   "Jaisalmer",
   "Jalandhar",
   "Jalgaon",
   "Jammu",
   "Jamnagar",
   "Jamshedpur",
   "Jodhpur",
   "Kakinada",
   "Kandla",
   "Kannur",
   "Kanpur",
   "Karnal",
   "Kasargod",
   "Kavaratti",
   "Kharagpur",
   "Kohima",
   "Kolar",
   "Kolhapur",
   "Kollam",
   "Kota",
   "Kottayam",
   "Kozhikode / Calicut",
   "Kulu/Manali",
   "Kurnool",
   "Kurukshetra",
   "Lucknow",
   "Ludhiana",
   "Madurai",
   "Malappuram",
   "Mangalore",
   "Mathura",
   "Meerut",
   "Mohali",
   "Moradabad",
   "Mysore",
   "Nagercoil",
   "Nagpur",
   "Nasik",
   "Nellore",
   "Nizamabad",
   "Ooty",
   "Pallakad",
   "Panchkula",
   "Panipat",
   "Paradeep",
   "Pathanamthitta",
   "Pathankot",
   "Patiala",
   "Patna",
   "Pondicherry",
   "Porbandar",
   "Port Blair",
   "Puri",
   "Quilon",
   "Raipur",
   "Rajamundry",
   "Rajkot",
   "Ranchi",
   "Rohtak",
   "Roorkee",
   "Rourkela",
   "Salem",
   "Shillong",
   "Shimla",
   "Shimoga",
   "Sholapur",
   "Silchar",
   "Siliguri",
   "Silvassa",
   "Sonipat / Sonepat",
   "Srinagar",
   "Surat",
   "Thanjavur",
   "Thrissur / Trissur",
   "Thiruvananthapuram / Trivandrum",
   "Tirunalveli",
   "Tirupati",
   "Trichy",
   "Tuticorin",
   "Udaipur",
   "Ujjain",
   "Valsad",
   "Vapi",
   "Varanasi",
   "Vellore",
   "Vijayawada",
   "Visakhapatnam",
   "Warangal",
   "Wayanad",
   "Yamunanagar",
   "Other India",
   "Afghanistan",
   "Australia",
   "Bahrain",
   "Bangladesh",
   "Belgium",
   "Canada",
   "China",
   "Egypt",
   "France",
   "Germany",
   "Gulf",
   "Hongkong",
   "Indonesia",
   "Iraq",
   "Ireland",
   "Japan",
   "Jordan",
   "Kuwait",
   "Lebanon",
   "Macau",
   "Malaysia",
   "Maldives",
   "Mauritius",
   "Mexico",
   "Nepal",
   "Netherlands",
   "New Zealand",
   "Oman",
   "Pakistan",
   "Philippines",
   "Qatar",
   "Russia",
   "Saudi Arabia",
   "Singapore",
   "South Africa",
   "South Korea",
   "Spain",
   "SriLanka",
   "Sweden",
   "Switzerland",
   "Taiwan",
   "Thailand",
   "UK",
   "United Arab Emirates",
   "US",
   "Vietnam",
   "Yemen",
   "Zimbabwe",
   "Other International"
   ]
